export const REFINEMENTTYPE: {}[] = [
  {name: "Normal", checked: false},
  {name: "Fire", checked: false},
  {name: "Water", checked: false},
  {name: "Grass", checked: false},
  {name: "Electric", checked: false},
  {name: "Ice", checked: false},
  {name: "Fighting", checked: false},
  {name: "Poison", checked: false},
  {name: "Ground", checked: false},
  {name: "Flying", checked: false},
  {name: "Psychic", checked: false},
  {name: "Bug", checked: false},
  {name: "Rock", checked: false},
  {name: "Ghost", checked: false},
  {name: "Dragon", checked: false},
  {name: "Dark", checked: false},
  {name: "Steel", checked: false},
  {name: "Fairy", checked: false},
];